### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by aha999** [zkldi/playground#2]
Add templates on github for issues, like Feature, Bug etc.

Issue templates will enable you to get more clear information in a better format.

Here is a general idea and some instructions on how to make it functional: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by zkldi** [comment]
Probably not. This is a monorepo which will contain more projects in the future. I'll look into implementing this if it gets out of hand.

**Comment by aha999** [comment]
It can be as simple as:

A user wants to submit a feature idea: clicks on a New Issue button, which shows 2 options: Feature Request, Bug report

User selects Feature request.

Then a pre-written text is visible like: 

Is your request related to a problem?
What is the solution you are proposing ?
Additional info:

This is just an example, but there are well written templates, so users can better solve it so the issue is more clear and doesn't need much explanation.
